apiVersion: v1
kind: Pod
metadata:
  name: cloudknife
spec:
  containers:
  - name: cloudknife
    image: quay.io/datawire/cloudknife
    imagePullPolicy: Always
    volumeMounts:
    - name: docker
      mountPath: "/var/run/docker.sock"
  volumes:
    - name: docker
      hostPath:
        path: "/var/run/docker.sock"
